import { Lead, ImportBatch, Note, Reminder, ContactLog, Visit } from "../types";
import { DEFAULT_SCORE_CONFIG } from "../types";
import { calculatePriorityScore, checkHasWebsite, checkHasSocialMedia } from "./score";

export function generateSampleData(): {
  leads: Lead[];
  batches: ImportBatch[];
  notes: Note[];
  reminders: Reminder[];
  contactLogs: ContactLog[];
  visits: Visit[];
} {
  const batchId = "batch_sample_pt_01";
  const now = new Date();
  const isoNow = now.toISOString();

  const rawSampleLeads: Partial<Lead>[] = [
    {
      id: "lead_pt_1",
      name: "Tasca do Marquês",
      type: "Restaurante Tradicional Português",
      category: "Restaurante",
      phone: "+351 213 456 789",
      email: "",
      address: "Rua das Flores 42, 1200-195 Lisboa",
      street: "Rua das Flores 42",
      city: "Lisboa",
      state: "Lisboa",
      postalCode: "1200-195",
      country: "Portugal",
      latitude: 38.7112,
      longitude: -9.1432,
      website: "",
      facebook: "https://facebook.com/tascadomarqueslisboa",
      instagram: "https://instagram.com/tascadomarques_lx",
      rating: 4.7,
      reviews: 412,
      businessStatus: "OPERATIONAL",
      about: "Petiscos tradicionais portugueses, polvo à lagareiro e bife à casa no centro de Lisboa.",
      status: "NOVO",
      photosCount: 24,
      photo: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&auto=format&fit=crop&q=80",
    },
    {
      id: "lead_pt_2",
      name: "Churrasqueira Ribeira",
      type: "Churrasqueira & Grelhados",
      category: "Restaurante",
      phone: "+351 222 987 654",
      email: "ribeira.grelhados@sapo.pt",
      address: "Cais da Ribeira 18, 4050-510 Porto",
      street: "Cais da Ribeira 18",
      city: "Porto",
      state: "Porto",
      postalCode: "4050-510",
      country: "Portugal",
      latitude: 41.1408,
      longitude: -8.6133,
      website: "",
      facebook: "https://facebook.com/churrasqueiraribeiraporto",
      instagram: "https://instagram.com/churrasqueira_ribeira",
      rating: 4.6,
      reviews: 680,
      businessStatus: "OPERATIONAL",
      about: "Especialidade em frango de churrasco, costeletão maturado e francesinhas artesanais com vista para o Douro.",
      status: "CONTACTADO",
      photosCount: 38,
      photo: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80",
    },
    {
      id: "lead_pt_3",
      name: "Pastelaria & Café Progresso",
      type: "Cafetaria e Pastelaria Fina",
      category: "Café",
      phone: "+351 253 112 334",
      email: "",
      address: "Avenida da Liberdade 88, 4710-250 Braga",
      street: "Avenida da Liberdade 88",
      city: "Braga",
      state: "Braga",
      postalCode: "4710-250",
      country: "Portugal",
      latitude: 41.5503,
      longitude: -8.4201,
      website: "",
      facebook: "https://facebook.com/cafeprogressobraga",
      instagram: "https://instagram.com/cafeprogresso_braga",
      rating: 4.8,
      reviews: 520,
      businessStatus: "OPERATIONAL",
      about: "Pastelaria tradicional de fabrico próprio, tíbias de Braga e fidalguinhos com torrefação de café artesanal.",
      status: "RESPONDEU",
      photosCount: 15,
      photo: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=600&auto=format&fit=crop&q=80",
    },
    {
      id: "lead_pt_4",
      name: "Marisqueira Sol de Faro",
      type: "Marisqueira",
      category: "Restaurante",
      phone: "+351 289 555 777",
      email: "info@marisqueirafaro.pt",
      address: "Rua do Bocage 15, 8000-120 Faro",
      street: "Rua do Bocage 15",
      city: "Faro",
      state: "Faro",
      postalCode: "8000-120",
      country: "Portugal",
      latitude: 37.0194,
      longitude: -7.9307,
      website: "https://www.marisqueirafaro.pt",
      facebook: "https://facebook.com/soldefaro",
      instagram: "https://instagram.com/soldefaro",
      rating: 4.4,
      reviews: 310,
      businessStatus: "OPERATIONAL",
      about: "Marisco fresco da Ria Formosa, cataplana algarvia e arroz de lingueirão.",
      status: "REUNIAO",
      photosCount: 42,
      photo: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80",
    },
    {
      id: "lead_pt_5",
      name: "O Forno de Coimbra",
      type: "Padaria & Pizzaria Artesanal",
      category: "Restaurante",
      phone: "+351 239 881 223",
      email: "",
      address: "Largo da Portagem 7, 3000-337 Coimbra",
      street: "Largo da Portagem 7",
      city: "Coimbra",
      state: "Coimbra",
      postalCode: "3000-337",
      country: "Portugal",
      latitude: 40.2089,
      longitude: -8.4292,
      website: "",
      facebook: "https://facebook.com/ofornodecoimbra",
      rating: 4.5,
      reviews: 295,
      businessStatus: "OPERATIONAL",
      about: "Pizzas em forno de lenha e pão de fermentação lenta no coração de Coimbra.",
      status: "NOVO",
      photosCount: 19,
      photo: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80",
    },
    {
      id: "lead_pt_6",
      name: "Taberna do Bacalhau",
      type: "Restaurante Típico",
      category: "Restaurante",
      phone: "+351 234 321 000",
      email: "contato@tabernabacalhau.com",
      address: "Canal Central 22, 3810-111 Aveiro",
      street: "Canal Central 22",
      city: "Aveiro",
      state: "Aveiro",
      postalCode: "3810-111",
      country: "Portugal",
      latitude: 40.6405,
      longitude: -8.6538,
      website: "https://tabernabacalhau.com",
      facebook: "",
      instagram: "https://instagram.com/tabernadobacalhau_aveiro",
      rating: 4.6,
      reviews: 450,
      businessStatus: "OPERATIONAL",
      about: "Bacalhau com natas, à Brás e à Lagareiro junto aos canais da ria de Aveiro.",
      status: "ANGIARIADO",
      photosCount: 30,
      photo: "https://images.unsplash.com/photo-1551218808-94e220e084d2?w=600&auto=format&fit=crop&q=80",
    },
    {
      id: "lead_pt_7",
      name: "Café & Gelataria do Parque",
      type: "Gelataria e Creparia",
      category: "Gelataria",
      phone: "+351 265 771 900",
      email: "",
      address: "Avenida Luísa Todi 114, 2900-452 Setúbal",
      street: "Avenida Luísa Todi 114",
      city: "Setúbal",
      state: "Setúbal",
      postalCode: "2900-452",
      country: "Portugal",
      latitude: 38.5244,
      longitude: -8.8931,
      website: "",
      facebook: "https://facebook.com/gelatariadoparque_setubal",
      instagram: "https://instagram.com/gelatariadoparque",
      rating: 4.9,
      reviews: 730,
      businessStatus: "OPERATIONAL",
      about: "Gelados 100% artesanais italianos, crepes e waffles quentes na baixa de Setúbal.",
      status: "NOVO",
      photosCount: 28,
      photo: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=600&auto=format&fit=crop&q=80",
    },
    {
      id: "lead_pt_8",
      name: "Aconchego Alentejano",
      type: "Restaurante Regional",
      category: "Restaurante",
      phone: "+351 266 741 852",
      email: "info@aconchegoalentejano.pt",
      address: "Praça do Giraldo 12, 7000-508 Évora",
      street: "Praça do Giraldo 12",
      city: "Évora",
      state: "Évora",
      postalCode: "7000-508",
      country: "Portugal",
      latitude: 38.5714,
      longitude: -7.9094,
      website: "",
      facebook: "https://facebook.com/aconchegoalentejano",
      instagram: "https://instagram.com/aconchegoalentejano",
      rating: 4.8,
      reviews: 580,
      businessStatus: "OPERATIONAL",
      about: "Carne de porco à alentejana, açordas e ensopado de borrego no centro histórico de Évora.",
      status: "FOLLOW_UP",
      photosCount: 22,
      photo: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&auto=format&fit=crop&q=80",
    },
  ];

  const leads: Lead[] = rawSampleLeads.map((raw) => {
    const hasWebsite = checkHasWebsite(raw.website);
    const hasSocialMedia = checkHasSocialMedia(raw);
    const { score, breakdown } = calculatePriorityScore(raw, DEFAULT_SCORE_CONFIG);

    return {
      ...(raw as any),
      batchId,
      batchName: "Lote Inicial - Negócios Locais Portugal",
      hasWebsite,
      hasSocialMedia,
      priorityScore: score,
      scoreBreakdown: breakdown,
      createdAt: isoNow,
      updatedAt: isoNow,
    };
  });

  const batches: ImportBatch[] = [
    {
      id: batchId,
      name: "Lote Inicial - Negócios Locais Portugal",
      originalFileName: "outscraper_restaurantes_pt_sample.xlsx",
      importedAt: isoNow,
      totalProcessed: leads.length,
      newLeadsCount: leads.length,
      updatedLeadsCount: 0,
      ignoredCount: 0,
    },
  ];

  const notes: Note[] = [
    {
      id: "note_1",
      leadId: "lead_pt_2",
      text: "Falei com o proprietário Sr. Carlos por telefone. Ficou muito recetivo à ideia de ter uma página para reservas e menu digital. Pediu proposta por email.",
      createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
      updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    },
    {
      id: "note_2",
      leadId: "lead_pt_3",
      text: "Responderam ao email manifestando interesse em renovar a imagem digital e adicionar loja online para encomendas de pastelaria.",
      createdAt: new Date(Date.now() - 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 86400000).toISOString(),
    },
  ];

  const inTwoDays = new Date(Date.now() + 86400000 * 2);
  const overdueYesterday = new Date(Date.now() - 86400000);

  const reminders: Reminder[] = [
    {
      id: "rem_1",
      leadId: "lead_pt_2",
      leadName: "Churrasqueira Ribeira",
      leadCity: "Porto",
      dueAt: inTwoDays.toISOString(),
      text: "Ligar ao Sr. Carlos para confirmar receção da proposta de website.",
      status: "PENDENTE",
    },
    {
      id: "rem_2",
      leadId: "lead_pt_1",
      leadName: "Tasca do Marquês",
      leadCity: "Lisboa",
      dueAt: overdueYesterday.toISOString(),
      text: "Fazer primeira abordagem presencial ou por telefone (horário antes do almoço: 11h30).",
      status: "PENDENTE",
    },
  ];

  const contactLogs: ContactLog[] = [
    {
      id: "cl_1",
      leadId: "lead_pt_2",
      type: "TELEFONE",
      date: new Date(Date.now() - 86400000 * 2).toISOString(),
      notes: "Primeiro contacto telefónico. Conversa de 5 minutos com o dono.",
    },
    {
      id: "cl_2",
      leadId: "lead_pt_3",
      type: "EMAIL",
      date: new Date(Date.now() - 86400000 * 3).toISOString(),
      notes: "Envio de pitch personalizado via email.",
    },
  ];

  const visits: Visit[] = [
    {
      id: "vis_1",
      leadId: "lead_pt_1",
      leadName: "Tasca do Marquês",
      leadCity: "Lisboa",
      leadAddress: "Rua das Flores 42, 1200-195 Lisboa",
      plannedDate: new Date(Date.now() + 86400000 * 3).toISOString(),
      status: "PENDENTE",
      resultNotes: "",
    },
  ];

  return {
    leads,
    batches,
    notes,
    reminders,
    contactLogs,
    visits,
  };
}
